// <auto-generated />
namespace Ecology.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddWater : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWater));
        
        string IMigrationMetadata.Id
        {
            get { return "202202101259456_AddWater"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
